site_name: Zen Dock 1.0 for Blender
site_description: Zen Dock 1.0 for Blender Documentation
nav:
    - Getting Started:
        - Introduction: index.md
        - Installation: installation.md
    - Modules:
        - Toggle: toggle.md
        - Restore minimized: min_restore.md
        - System: system.md
    - Additional:
        - Preferences: preferences.md
        - Help: help.md
        - Downloads: downloads.md
        - Changelog: changelog.md

docs_dir: mkdocs
site_dir: docs
theme: readthedocs

markdown_extensions:
    - smarty
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: 